permalink: /:year:month:day/:title
url: #https://solohack3r.github.io/
baseurl: /project

# variables
name: Solohack3r Studios - Indie Game Developer
description: An indie game developer focusing on retro open world RPGs.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true